[tool.poetry]
name = "invoicing"
version = "0.1.0"
description = "Automated Peppol- and EN16931- compliant invoicing, along with PDFs"
authors = ["jtbr <jtbr@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
lxml = "^5.4"
python-dateutil = "^2.9"
python-docx = "^1.2"
requests = {version = "^2.31", optional = true}

[tool.poetry.extras]
odoo = ["requests"]
peppol = ["requests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
